[server]
host = "127.0.0.1"
port = 8082
domain = "story-rs.dev"
jwt_secret="secret"

[database]
driver = "mysql"
username = "homestead"
password = "secret"
host = "127.0.0.1"
port = 33060
database = "homestead"

